(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(*Notation`AutoLoadNotationPalette=False;*)
BeginPackage["LatticePlaneDebug`","Notation`"(*,"NDSolve`FEM`","OpenCascadeLink`","MaXrd`"*)];
(*Notation`AutoLoadNotationPalette=True;*)
Unprotect@@Names["LatticePlaneDebug`*"];
Unprotect[Evaluate[Context[]<>"*"]];
ClearAll@@Names["LatticePlaneDebug`*"];
ClearAll["LatticePlaneDebug`Private`*"];


(* ::Input::Initialization:: *)
(*Off[General::spell1];
Off[Symbolize::boxSymbolExists];(*subscripted symbols*)*)
Symbolize[ParsedBoxWrapper[SubscriptBox["_","_"]]];(*this is the internal representation of Symbolize suggested by Jason Harris for Mma package, see https://groups.google.com/g/comp.soft-sys.math.mathematica/c/rhIhi-v_D5E?pli=1*)
(*On[Symbolize::boxSymbolExists];*)


(* ::Input::Initialization:: *)
ParseHKL::usage="ParseHKL[hklIn]";


(* ::Input::Initialization:: *)
Begin["`Private`"];


(* ::Input::Initialization:: *)
ParseHKL[hklIn_]:=Module[{hkl},
hkl=hklIn/.{OverBar->Minus,0->Indeterminate};
If[Length@hkl==4,hkl=hkl[[{1,2,4}]],hkl]
]


(* ::Input::Initialization:: *)
End[];
(*On[General::spell1];*)
Protect@@Names["LatticePlaneDebug`*"];
(*Protect[Evaluate[Context[]<>"*"]];*)
EndPackage[];



